--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/BetterConfig
build-by-default: true
branches:
- main
projects:
  BetterConfig:
    path: ""
    model: virion
    type: library
    includeDirs:
      vendor: vendor
...
